tp5/Controllers/CadeteController.cs
namespace tp5.Controllers;
public class CadeteController : Controller
{
    private readonly ILogger<CadeteController> _logger;
    private readonly IMapper _mapper;

    private readonly IRepositorioUsuario _repositorioUsuario;

    private static int id;
    public CadeteController(ILogger<CadeteController> logger, IRepositorioUsuario repositorioUsuario,IMapper mapper)
    {
        _logger = logger;
        _repositorioUsuario = repositorioUsuario;
        _mapper = mapper;
    }
    public IActionResult Index()
    {
        try
        {
            if (HttpContext.Session.GetInt32(SessionRol) != (int)Rol.Administrador)
            {
                return RedirectToAction("Index", "Home");
            }

            var cadetes = _repositorioUsuario.BuscarTodosPorRol(Rol.Cadete);
            var cadetesViewModel = _mapper.Map<List<UsuarioViewModel>>(cadetes);
            return View(cadetesViewModel);
        }
        catch (Exception e)
        {
            _logger.LogError("Error al acceder al Index {Error}", e.Message);
            return View("Error");
        }
    }

    [HttpGet]
    public IActionResult AltaCadete()
    {
        try
        {
            if (HttpContext.Session.GetInt32(SessionRol) != (int)Rol.Administrador)
            {
                return RedirectToAction("Index", "Home");
            }

            return View("AltaCadete");
        }
        catch (Exception e)
        {
            _logger.LogError("Error al acceder el Alta de Cadete {Error}", e.Message);
            return View("Error");
        }
    }

    [HttpPost]
    public IActionResult AltaCadete(UsuarioViewModel cadeteViewModel)
    {
        try
        {
            if (HttpContext.Session.GetInt32(SessionRol) != (int)Rol.Administrador)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                var cadete = _mapper.Map<Usuario>(cadeteViewModel);
                _repositorioUsuario.Insertar(cadete);
            }
            else
            {
                var errores = ModelState.Values.SelectMany(x => x.Errors);
                Console.WriteLine(errores);
            }

            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            _logger.LogError("Error al acceder el Alta de Cadete {Error}", e.Message);
            return View("Error");
        }
    }

     [HttpGet]
    public IActionResult ModificarCadete(int id)
    {
         try
        {
            if (HttpContext.Session.GetInt32(SessionRol) != (int)Rol.Administrador)
            {
                return RedirectToAction("Index", "Home");
            }

            var cadete = _repositorioUsuario.BuscarPorId(id);
            if (cadete is null) return RedirectToAction("Index");
            var cadeteViewModel = _mapper.Map<UsuarioViewModel>(cadete);
            return View(cadeteViewModel);
        }
        catch (Exception e)
        {
            _logger.LogError("Error al acceder el Modificar Cadete {Error}", e.Message);
            return View("Error");
        }
    }

    [HttpPost]
    public IActionResult ModificarCadete(UsuarioModificadoViewModel cadeteViewModel)
    {
        try
        {
            if (HttpContext.Session.GetInt32(SessionRol) != (int)Rol.Administrador)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                var cadete = _mapper.Map<Usuario>(cadeteViewModel);
                _repositorioUsuario.Actualizar(cadete);
            }
            else
            {
                var errores = ModelState.Values.SelectMany(x => x.Errors);
                Console.WriteLine(errores);
            }

            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            _logger.LogError("Error al acceder el Modificar Cadete {Error}", e.Message);
            return View("Error");
        }
    }

    [HttpGet]
    public IActionResult BajaCadete(int id)
    {
        try
        {
            if (HttpContext.Session.GetInt32(SessionRol) != (int)Rol.Administrador)
            {
                return RedirectToAction("Index", "Home");
            }

            _repositorioUsuario.Eliminar(id);
            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            _logger.LogError("Error al acceder el Baja Cadete {Error}", e.Message);
            return View("Error");
        }
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        if (HttpContext.Session.GetInt32(SessionRol) != (int)Rol.Administrador)
        {
            return RedirectToAction("Index", "Home");
        }

        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }


}

tp5/Controllers/PedidoController.cs
namespace tp5.Controllers;
public class PedidoController : Controller
{
    private readonly ILogger<PedidoController> _logger;
    private readonly IMapper _mapper;
    private readonly IRepositorioPedido _repositorioPedido;
    private readonly IRepositorioUsuario _repositorioUsuario;
    public PedidoController(ILogger<PedidoController> logger, IRepositorioPedido repositorioPedido,
        IRepositorioUsuario repositorioUsuario, IMapper mapper)
    {
        _logger = logger;
        _repositorioPedido = repositorioPedido;
        _repositorioUsuario = repositorioUsuario;
        _mapper = mapper;
    }

    [HttpGet]
    public IActionResult Index()
    {
        try
        {
            // var sesionRol = (Rol)HttpContext.Session.GetInt32(SessionRol); //antes de la presentacion
            int? RolActual = HttpContext.Session.GetInt32(SessionRol); //correccion post-presentacion en vez de castear, ahora si redirige al index
            switch (RolActual)
            {
                case 2:
                {
                    var pedidos = _repositorioPedido.BuscarTodos();
                    var pedidosViewModel = _mapper.Map<List<PedidoViewModel>>(pedidos);

                    foreach (var pedido in pedidosViewModel)
                    {
                        var clienteId = int.Parse(pedido.Cliente);
                        var idCadete = int.Parse(pedido.Cadete);

                        pedido.Cliente = _repositorioUsuario.BuscarPorId(clienteId)?.Nombre;
                        pedido.Cadete = _repositorioUsuario.BuscarPorId(idCadete)?.Nombre;
                    }

                    return View(pedidosViewModel);
                }
                case 0:
                {
                    var idCadete = (int)HttpContext.Session.GetInt32(SessionId);
                    var pedidos = _repositorioPedido.BuscarTodosPorUsuarioYRol(idCadete, Rol.Cadete); 
                    var pedidosViewModel = _mapper.Map<List<PedidoViewModel>>(pedidos);

                    foreach (var pedido in pedidosViewModel)
                    {
                        var idCliente = int.Parse(pedido.Cliente);
                        pedido.Cliente = _repositorioUsuario.BuscarPorId(idCliente)?.Nombre;
                    }

                    return View(pedidosViewModel);
                }
                case 1:
                {
                    var idCliente = (int)HttpContext.Session.GetInt32(SessionId);
                    var pedidos = _repositorioPedido.BuscarTodosPorUsuarioYRol(idCliente, Rol.Cliente); 
                    var pedidosViewModel = _mapper.Map<List<PedidoViewModel>>(pedidos);

                    foreach (var pedido in pedidosViewModel)
                    {
                        var idCadete = int.Parse(pedido.Cadete);
                        pedido.Cadete = _repositorioUsuario.BuscarPorId(idCadete)?.Nombre;
                    }

                    return View(pedidosViewModel);
                }
                default:
                    return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Index", "Home");
        }
        catch (Exception e)
        {
            _logger.LogError("Error al acceder el Index {Error}", e.Message);
            return View("Error");
        }
    }

    [HttpGet]
    public IActionResult AltaPedido()
    {
        try
        {
            var sesionRol = HttpContext.Session.GetInt32(SessionRol);
            if (sesionRol != (int)Rol.Administrador)
                return RedirectToAction("Index", "Home");

            var cadetes = _repositorioUsuario.BuscarTodosPorRol(Rol.Cadete);
            var clientes = _repositorioUsuario.BuscarTodosPorRol(Rol.Cliente);
            var cadetesViewModel = _mapper.Map<List<UsuarioViewModel>>(cadetes);
            var clientesViewModel = _mapper.Map<List<UsuarioViewModel>>(clientes);
            var pedidoAltaViewModel = new PedidoAltaViewModel(cadetesViewModel, clientesViewModel);
            return View(pedidoAltaViewModel);
        }
        catch (Exception e)
        {
            _logger.LogError("Error al acceder el Alta Pedido {Error}", e.Message);
            return View("Error");
        }
    }

    [HttpPost]
    public IActionResult AltaPedido(PedidoViewModel pedidoViewModel)
    {
        try
        {
            var sesionRol = HttpContext.Session.GetInt32(SessionRol);
            if (sesionRol != (int)Rol.Administrador)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                var pedido = _mapper.Map<Pedido>(pedidoViewModel);
                _repositorioPedido.Insertar(pedido);
            }
            else
            {
                var errores = ModelState.Values.SelectMany(x => x.Errors);
                Console.WriteLine(errores);
            }

            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            _logger.LogError("Error al acceder el Alta Pedido {Error}", e.Message);
            return View("Error");
        }
    }

    [HttpGet]
    public IActionResult ModificarPedido(int id)
    {
        try
        {
            if(!HttpContext.Session.IsAvailable)
            {
                return RedirectToAction("Index", "Home");
            }

            var pedido = _repositorioPedido.BuscarPorId(id);

            var cadetes = _repositorioUsuario.BuscarTodosPorRol(Rol.Cadete);
            var cadetesViewModel = _mapper.Map<List<UsuarioViewModel>>(cadetes);

            var clientes = _repositorioUsuario.BuscarTodosPorRol(Rol.Cliente);
            var clientesViewModel = _mapper.Map<List<UsuarioViewModel>>(clientes);

            var pedidoModificadoViewModel = _mapper.Map<PedidoModificadoViewModel>(pedido);
            pedidoModificadoViewModel.Cadetes = cadetesViewModel;
            pedidoModificadoViewModel.Clientes = clientesViewModel;

            return View(pedidoModificadoViewModel);
        }
        catch (Exception e)
        {
            _logger.LogError("Error al acceder el Modificar Pedido {Error}", e.Message);
            return View("Error");
        }
    }

    [HttpPost]
    public IActionResult ModificarPedido(PedidoViewModel pedidoViewModel)
    {
        try
        {
            if(!HttpContext.Session.IsAvailable)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                var pedido = _mapper.Map<Pedido>(pedidoViewModel);
                _repositorioPedido.Actualizar(pedido);
            }
            else
            {
                var errores = ModelState.Values.SelectMany(x => x.Errors);
                Console.WriteLine(errores);
            }

            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            _logger.LogError("Error al acceder el Modificar Pedido {Error}", e.Message);
            return View("Error");
        }
    }

    [HttpGet]
    public IActionResult BajaPedido(int id)
    {
        try
        {
            var sesionRol = HttpContext.Session.GetInt32(SessionRol);
            if (sesionRol != (int)Rol.Administrador)
            {
                return RedirectToAction("Index", "Home");
            }

            _repositorioPedido.Eliminar(id);
            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            _logger.LogError("Error al acceder el Baja Pedido {Error}", e.Message);
            return View("Error");
        }
    }

    [HttpGet]
    public IActionResult listarPedidosCadete(int idCadete, string nombreCadete){
        try
        {
            string rolUsuario = HttpContext.Session.GetString(SessionRol);
            if(rolUsuario == null) return RedirectToAction("Index","Home");

            var pedidos = _repositorioPedido.BuscarPedidosPorCadete(idCadete);
            var pedidosViewModel = _mapper.Map<List<PedidoViewModel>>(pedidos);

            PedidosCadeteViewModel listarPedidosCadeteViewModel = new PedidosCadeteViewModel(nombreCadete,pedidosViewModel);

            return View(listarPedidosCadeteViewModel);
        }
        catch (System.Exception ex)
        {
            ViewBag.Error = ex.Message; 
            return View(new PedidosCadeteViewModel());
        }
    }

    [HttpGet]
    public IActionResult listarPedidosCliente(int idCliente, string nombreCliente){
        try
        {
            string rolUsuario = HttpContext.Session.GetString(SessionRol);
            if(rolUsuario == null) return RedirectToAction("Index","Home");

            var pedidos = _repositorioPedido.BuscarPedidosPorCliente(idCliente);
            var pedidosViewModel = _mapper.Map<List<PedidoViewModel>>(pedidos);

            PedidosClienteViewModel listarPedidosClienteViewModel = new PedidosClienteViewModel(nombreCliente,pedidosViewModel);

            return View(listarPedidosClienteViewModel);
        }
        catch (System.Exception ex)
        {
            ViewBag.Error = ex.Message; 
            return View(new PedidosCadeteViewModel());
        }
    }
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        var sesionRol = HttpContext.Session.GetInt32(SessionRol);
        if (sesionRol != (int)Rol.Administrador)
        {
            return RedirectToAction("Index", "Home");
        }else{
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

tp5/Views/Cadete/AltaCadete.cshtml
@model Cadete

<h1>@ViewData["Title"]</h1>
<body>
    <header>
        <main>
            <h1>Registrar Cadete</h1>
            <form asp-controller="Cadete" asp-action="AltaCadeteExito" method="post" >
                <label for="nombre">Nombre:</label>
                <input type="text" id="nombre" name="nombre" placeholder="Escriba el nombre del cadete">

                <label for="direccion">Direccion:</label>
                <input type="text" id="direccion" name="direccion" placeholder="Escriba la direccion del cadete">

                <label for="telefono">Telefono:</label>
                <input type="tel" id="telefono" name="telefono">

                <input type="submit" value="Cargar">
                <input type="reset" value="Borrar">
            </form>

        </main>
    </header>
</body>

tp5/Views/Cadete/Index.cshtml
@model List<UsuarioViewModel>

<h2>Lista de Cadetes</h2>

<a class="btn btn-primary btn-sm" href="/Cadete/AltaCadete">Crear nuevo Cadete</a>

<section>
    <article>

        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Dirección</th>
                <th>Teléfono</th>
                <th>Acciones</th>
            </tr>
            </thead>

            <tbody>
            @foreach (var cadete in Model)
            {
                <tr>
                    <td>@cadete.Id</td>
                    <td>@cadete.Nombre</td>
                    <td>@cadete.Direccion</td>
                    <td>@cadete.Telefono</td>
                    <td>
                        <a class="btn btn-primary btn-sm" asp-controller="Pedido" asp-action="listarPedidosCadete" asp-route-idCadete="@cadete.Id" asp-route-nombreCadete="@cadete.Nombre">Listar</a>
                        <a class="btn btn-primary btn-sm" asp-controller="Cadete" asp-action="ModificarCadete" asp-route-id="@cadete.Id">Editar</a>
                        <a class="btn btn-danger btn-sm" asp-controller="Cadete" asp-action="BajaCadete" asp-route-id="@cadete.Id">Eliminar</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>

    </article>
</section>

tp5/Views/Cadete/ModificarCadete.cshtml
@model UsuarioViewModel

@{
    ViewBag.Title = "Modificar Cadete";
    Layout = "_Layout";
}

<body>
<header>
    <main>
        <h2>@ViewBag.Title</h2>
        <form asp-controller="Cadete" asp-action="ModificarCadete" method="post">

            @Html.HiddenFor(model => model.Id)

            <div class="row mb-3">
                <label class="col-sm-3 col-form-label" asp-for="Nombre">Nombre: </label>
                <div class="col-sm-6">
                    <input class="form-control" type="text" asp-for="Nombre" value="@Model.Nombre">
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-sm-3 col-form-label" asp-for="Direccion">Dirección:</label>
                <div class="col-sm-6">
                    <input class="form-control" type="text" asp-for="Direccion" value="@Model.Direccion">
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-sm-3 col-form-label" asp-for="Telefono">Teléfono</label>
                <div class="col-sm-6">
                    <input class="form-control" type="tel" asp-for="Telefono" value="@Model.Telefono">
                </div>
            </div>

            <div class="row mb-3">
                <div class="offset-sm-3 col-sm-3 d-grid">
                    <input class="btn btn-primary" type="submit" value="Modificar">
                </div>
                <div class="col-sm-3 d-grid">
                    <input class="btn btn-primary" type="reset" value="Borar">
                </div>
            </div>

        </form>
    </main>
</header>
</body>